baseURL = "https://blog.desgran.ge/"
#languageCode = "en-us"
title = "Remi Desgrange's blog"
theme="hugo-PaperMod"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true

[params]
    env = "production"
    description = 'Blog about tech, Python, GIS, OpenData, and maybe more.'
    author= "Rémi Desgrange"
    logo = "https://avatars3.githubusercontent.com/u/13271765"
    rss = true
    readingTime = true
    wordCount = true
    showRelatedPosts = true
    subtitle = "Blog about tech, Python, GIS, OpenData, and maybe more."
    commit = "https://github.com/RemiDesgrange/blog/tree/"
    selfHosted = true

[Author]
  name = "Rémi Desgrange"
  email = "remi+blog@desgran.ge"
  github = "RemiDesgrange"
  twitter = "DesgrangeRemi"
  linkedin = "rdesgrange"
  stackoverflow = "users/8204956/rémi-desgrange"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
