baseURL = "https://blog.desgrange.info/"
languageCode = "en-us"
title = "Remi Desgrange's blog"
theme="basics"



[params]
    description = 'Blog about tech, Python, GIS, OpenData, and maybe more.'
    author= "Rémi Desgrange"
	github= "RemiDesgrange"
  
